### ISSUE TITLE
校验对象里的属性时 v-verify="master.EMAIL"报错

### ISSUE THREAD

**Issue by JavaCodeMan** [mvpleung/vue-verify#1]
校验对象里的属性时 v-verify="master.EMAIL"报错
[Vue warn]: Error in directive verify bind hook: "TypeError: Cannot convert undefined or null to object"

**Comment by mvpleung** [comment]
v-verify 绑定的值是否为空

**Comment by JavaCodeMan** [comment]
请问有校验对象属性的demo吗？
下面是我的测试代码
data(){
 return{
              master:{
                     CONTENT:'',
                     EMAIL:''
               }
            }
        },
verify: {
          
          master:{
                CONTENT: [
                    {
                        test:"required",
                        message: "请输入您遇到的问题"
                    },
                    {
                        minLength:5,
                        message: "问题不得小于5个字符"
                    },
                    {
                        maxLength:200,
                        message: "问题不得多于200个字符"
                    }
                ],
                EMAIL:["required","email"]
           }
        },

**Comment by mvpleung** [comment]
刚去重新看了下，README和之前的版本串了，抱歉，请查看这里 [README](https://github.com/mvpleung/vue-verify/blob/master/README.md)
