### ISSUE TITLE
验证规则使用正则 会报错 Error in v-on handler: "SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by greatSou1** [mvpleung/vue-verify#3]

**Comment by mvpleung** [comment]
贴一下代码示例

**Comment by greatSou1** [comment]
![image](https://user-images.githubusercontent.com/40160450/61522653-ca463500-aa38-11e9-8b47-13e3460ee02e.png)
当数字符合的时候，正常，当输入非法字符串是,不会弹出错误，并控制台报错
![image](https://user-images.githubusercontent.com/40160450/61522788-109b9400-aa39-11e9-8db6-7870f54d4ed1.png)

**Comment by mvpleung** [comment]
我晚上看看

**Comment by mvpleung** [comment]
检查下你自己的代码，这个不是校验插件的问题
